### ISSUE TITLE
Shib log file integration with logstash

### ISSUE THREAD

**Issue by mmoayyed** [UniconLabs/shib-config-ui#1]
logstash is a tool for managing events and logs. You can use it to collect logs, parse 
them, and store them for later use (like, for searching).

http://logstash.net/

The idea is to configure this tool to integrate shib log files with logstash, provide a UI and perhaps elastic search.

**Comment by mmoayyed** [comment]
I might be able to take a look at this bit early next week.

**Comment by dima767** [comment]
There is already a UI for logstash in the Elastic search, namely Kibana: http://www.elasticsearch.org/overview/kibana/
