### ISSUE TITLE
Do not require $SHIBBOLETH_HOME

### ISSUE THREAD

**Issue by mmoayyed** [UniconLabs/shib-config-ui#4]
Instead, default to `/shibboleth/shibboleth-idp` which is the standard default location of the idp installer.

**Comment by mapgrady** [comment]
You mean "/opt/shibboleth-idp", correct?

On Oct 22, 2013, at 11:29 AM, Misagh Moayyed wrote:

> Instead, default to /shibboleth/shibboleth-idp which is the standard default location of the idp installer.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Michael A. Grady
Senior IAM Consultant, Unicon, Inc.

**Comment by scalding** [comment]
yeah, the default should be `/opt/shibboleth-idp`. I can make that change. I definitely won't give my sysadmin opinion about that :)

**Comment by scalding** [comment]
Should the application have the smarts to know whether an Idp installation exists at the location?

**Comment by mmoayyed** [comment]
I think that would be reasonable. Perhaps something as simple as not being able to find a particular xml file at a path would be a signal that the location is probably not an idp.

**Comment by scalding** [comment]
Well, it should already fail if it doesn't find the correct spring files. By the way, the instructions that are out there right now for running it aren't what I expect the end users to eventually run. When the project is a little more stable, I should get in and make a runnable package.
